# Generated by Django 6.0 on 2026-06-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_student_admission_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='remarks',
            field=models.TextField(blank=True, help_text='Remarks', null=True),
        ),
    ]
